# Generated by Django 2.2.10 on 2022-07-02 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220702_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 5, 51, 4, 706396, tzinfo=utc)),
        ),
    ]
